### ISSUE TITLE
determine how to get a record/core ID from create_credential_and_login

### ISSUE THREAD

**Issue by h00die** [h00die/metasploit-framework#13]
@jmartin-r7

I'm trying to figure out how to `create_credential_and_login`, then a `create_cracked_credential` for it. However I'm not seeing how I can get the core_id field back. Do I need to search for this credential I just made to pull that ID or did I miss something obvious?

https://github.com/h00die/metasploit-framework/blob/a489081743a993a3fced9c53be5fb7f1ebed1df1/lib/msf/core/auxiliary/ubiquiti.rb#L243

**Comment by h00die** [comment]
in my testing, `record` is being returned as `nil`

**Comment by h00die** [comment]
As a workaround, i decided to just fetch the record(s) again.
```
            framework.db.creds(cred).each do |c|
              create_cracked_credential(username: admin_name, password: admin_password, core_id: c.id)
            end
```

However, this then fails:
```
[-] Post failed: KeyError key not found: :address
[-] Call stack:
[-]   /var/lib/gems/2.5.0/gems/metasploit-credential-3.0.3/lib/metasploit/credential/creation.rb:551:in `fetch'
[-]   /var/lib/gems/2.5.0/gems/metasploit-credential-3.0.3/lib/metasploit/credential/creation.rb:551:in `create_credential_service'
[-]   /var/lib/gems/2.5.0/gems/metasploit-credential-3.0.3/lib/metasploit/credential/creation.rb:301:in `block in create_credential_login'
[-]   /var/lib/gems/2.5.0/gems/metasploit-credential-3.0.3/lib/metasploit/credential/creation.rb:621:in `retry_transaction'
[-]   /var/lib/gems/2.5.0/gems/metasploit-credential-3.0.3/lib/metasploit/credential/creation.rb:300:in `create_credential_login'
[-]   /metasploit-framework/lib/metasploit/framework/data_service/proxy/credential_data_proxy.rb:27:in `block (2 levels) in create_cracked_credential'
[-]   /var/lib/gems/2.5.0/gems/activerecord-4.2.11.1/lib/active_record/relation/delegation.rb:46:in `each'
[-]   /var/lib/gems/2.5.0/gems/activerecord-4.2.11.1/lib/active_record/relation/delegation.rb:46:in `each'
[-]   /metasploit-framework/lib/metasploit/framework/data_service/proxy/credential_data_proxy.rb:25:in `block in create_cracked_credential'
[-]   /metasploit-framework/lib/metasploit/framework/data_service/proxy/core.rb:166:in `data_service_operation'
[-]   /metasploit-framework/lib/metasploit/framework/data_service/proxy/credential_data_proxy.rb:15:in `create_cracked_credential'
[-]   /metasploit-framework/lib/msf/core/auxiliary/report.rb:26:in `create_cracked_credential'
[-]   /metasploit-framework/lib/msf/core/auxiliary/ubiquiti.rb:246:in `block (2 levels) in process_settings'
[-]   /var/lib/gems/2.5.0/gems/activerecord-4.2.11.1/lib/active_record/relation/delegation.rb:46:in `each'
[-]   /var/lib/gems/2.5.0/gems/activerecord-4.2.11.1/lib/active_record/relation/delegation.rb:46:in `each'
[-]   /metasploit-framework/lib/msf/core/auxiliary/ubiquiti.rb:245:in `block in process_settings'
[-]   /metasploit-framework/lib/msf/core/auxiliary/ubiquiti.rb:185:in `each'
[-]   /metasploit-framework/lib/msf/core/auxiliary/ubiquiti.rb:185:in `process_settings'
[-]   /metasploit-framework/lib/msf/core/auxiliary/ubiquiti.rb:328:in `block in unifi_config_eater'
[-]   /metasploit-framework/lib/msf/core/auxiliary/ubiquiti.rb:321:in `each'
[-]   /metasploit-framework/lib/msf/core/auxiliary/ubiquiti.rb:321:in `unifi_config_eater'
[-]   /metasploit-framework/modules/post/multi/gather/ubiquiti_unifi_backup.rb:69:in `extract_and_process_db'
[-]   /metasploit-framework/modules/post/multi/gather/ubiquiti_unifi_backup.rb:118:in `block in find_save_files'
[-]   /metasploit-framework/modules/post/multi/gather/ubiquiti_unifi_backup.rb:81:in `each'
[-]   /metasploit-framework/modules/post/multi/gather/ubiquiti_unifi_backup.rb:81:in `find_save_files'
[-]   /metasploit-framework/modules/post/multi/gather/ubiquiti_unifi_backup.rb:84:in `block in find_save_files'
[-]   /metasploit-framework/modules/post/multi/gather/ubiquiti_unifi_backup.rb:81:in `each'
[-]   /metasploit-framework/modules/post/multi/gather/ubiquiti_unifi_backup.rb:81:in `find_save_files'
[-]   /metasploit-framework/modules/post/multi/gather/ubiquiti_unifi_backup.rb:191:in `block in run'
[-]   /metasploit-framework/modules/post/multi/gather/ubiquiti_unifi_backup.rb:184:in `each'
[-]   /metasploit-framework/modules/post/multi/gather/ubiquiti_unifi_backup.rb:184:in `run'
```

My attempts to pass in the address fail as well, but nothing else ever does this anyways.  I've changed the code to pass an address to `create_credential_and_login` (it was `''`, but in debugging i set it), however that doesn't seem to make a difference either.

**Comment by jmartin-r7** [comment]
Thank you for detail, I will dig a bit and see what I can find that might move this forward.

**Comment by h00die** [comment]
@jmartin-r7 Any word on this?

**Comment by h00die** [comment]
@jmartin-r7 any word?

**Comment by jmartin-r7** [comment]
Sorry many things keep getting bumped ahead, will prioritize this week to get you some feedback.

**Comment by jmartin-r7** [comment]
Found a couple paths that may resolve these issues. https://github.com/rapid7/metasploit-credential/pull/139 should address the `Post failed: KeyError key not found: :address` error.  Once that releases, I have another branch in progress that may provide a solutions to the original core.  Will add more detail once I get that completed.

**Comment by h00die** [comment]
@jmartin-r7 Looks like you were right, https://github.com/h00die/metasploit-framework/issues/13#issuecomment-535286720 (removing the `address` field) and a rebase and we're working now.  Thanks!

**Comment by jmartin-r7** [comment]
https://github.com/rapid7/metasploit-framework/pull/12711 should have corrected the return value from `create_credential_and_login` to allow the following to work (note I have not tested this):
```
login = create_credential_and_login(cred)
unless admin_password.empty?
  create_cracked_credential(username: admin_name, password: admin_password, core_id: login.core.id)
end
```

**Comment by h00die** [comment]
you are 100% correct!
